"""add_fk_user_id

Revision ID: c5af6efb5917
Revises: ba0542d6c937
Create Date: 2026-06-04 02:00:40.917269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5af6efb5917'
down_revision: Union[str, None] = 'ba0542d6c937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('face_embeddings_embedding_idx', table_name='face_embeddings', postgresql_using='ivfflat')
    op.create_foreign_key(None, 'lecturers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'lecturers', type_='foreignkey')
    op.create_index('face_embeddings_embedding_idx', 'face_embeddings', ['embedding'], unique=False, postgresql_using='ivfflat')
    # ### end Alembic commands ###
